In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pop_df = pd.read_csv('population_data.csv')
pop_df.head()

,id,Country (or dependency),Population 2025,Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Median Age,Urban Pop %,World Share
0,1,India,1463865525,0.89%,12929734,492,2973190,"−495,753",1.94,28.8,37.1%,17.78%
1,2,China,1416096094,−0.23%,"−3,225,184",151,9388211,"−268,126",1.02,40.1,67.5%,17.20%
2,3,United States,347275807,0.54%,1849236,38,9147420,1230663,1.62,38.5,82.8%,4.22%
3,4,Indonesia,285721236,0.79%,2233305,158,1811570,"−39,509",2.10,30.4,59.6%,3.47%
4,5,Pakistan,255219554,1.57%,3950390,331,770880,"−1,235,336",3.50,20.6,34.4%,3.10%

In [4]:
pop_df.describe()
pop_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       233 non-null    int64
 1   Country (or dependency)  233 non-null    str
 2   Population 2025          233 non-null    int64
 3   Yearly Change            233 non-null    str
 4   Net Change               233 non-null    str
 5   Density (P/Km²)          233 non-null    int64
 6   Land Area (Km²)          233 non-null    int64
 7   Migrants (net)           233 non-null    str
 8   Fert. Rate               233 non-null    float64
 9   Median Age               233 non-null    float64
 10  Urban Pop %              210 non-null    str
 11  World Share              233 non-null    str
dtypes: float64(2), int64(4), str(6)
memory usage: 22.0 KB

In [5]:
# make all the column names in lowercase and replace spaces with underscores
pop_df.columns = pop_df.columns.str.lower().str.replace(' ', '_')

In [6]:
print(pop_df.columns)

Index(['id', 'country_(or_dependency)', 'population_2025', 'yearly_change',
       'net_change', 'density_(p/km²)', 'land_area_(km²)', 'migrants_(net)',
       'fert._rate', 'median_age', 'urban_pop_%', 'world_share'],
      dtype='str')

In [7]:
# select only african nations (inlclude all african nations) alphabetically 
african_nations = [
    "Algeria",
    "Angola",
    "Benin",
    "Botswana",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Comoros",
    "Congo",
    "DR Congo",
    "Côte d'Ivoire",
    "Djibouti",
    "Egypt",
    "Equatorial Guinea",
    "Eritrea",
    "Eswatini",
    "Ethiopia",
    "Gabon",
    "Gambia",
    "Ghana",
    "Guinea",
    "Guinea-Bissau",
    "Kenya",
    "Lesotho",
    "Liberia",
    "Libya",
    "Madagascar",
    "Malawi",
    "Mali",
    "Mauritania",
    "Mauritius",
    "Morocco",
    "Mozambique",
    "Namibia",
    "Niger",
    "Nigeria",
    "Rwanda",
    "Western Sahara",
    "Sao Tome & Principe",
    "Senegal",
    "Seychelles",
    "Sierra Leone",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Sudan",
    "Tanzania",
    "Togo",
    "Tunisia",
    "Uganda",
    "Zambia",
    "Saint Helena",
    "Mayotte",
    "Réunion",
    "Zimbabwe"
]
# add the remaining african nations. The list is not exhaustive.
african_df = pop_df[pop_df['country_(or_dependency)'].isin(african_nations)]
print(f'There are {african_df["country_(or_dependency)"].nunique()} African nations in the dataset.')

There are 58 African nations in the dataset.

In [8]:
# count african nations in the dataset
african_df = pop_df[pop_df['country_(or_dependency)'].isin(african_nations)]
print(f'There are {african_df["country_(or_dependency)"].nunique()} African nations in the dataset.')

There are 58 African nations in the dataset.

In [9]:
# select only african nations data fro analyis from the dataset
african_df = pop_df[pop_df['country_(or_dependency)'].isin(african_nations)]
african_df.head()

,id,country_(or_dependency),population_2025,yearly_change,net_change,density_(p/km²),land_area_(km²),migrants_(net),fert._rate,median_age,urban_pop_%,world_share
5,6,Nigeria,237527782,2.08%,4848304,261,910770,"−15,258",4.30,18.1,54.9%,2.89%
9,10,Ethiopia,135472051,2.58%,3412284,135,1000000,24054,3.81,19.1,22.5%,1.65%
12,13,Egypt,118365995,1.57%,1827737,119,995450,"−57,305",2.71,24.5,40.9%,1.44%
14,15,DR Congo,112832473,3.25%,3556208,50,2267050,"−27,309",5.90,15.8,45%,1.37%
20,21,Tanzania,70545865,2.9%,1985708,80,885800,"−12,730",4.47,17.5,40%,0.86%

In [10]:
print(african_df.columns)
print(african_df)

Index(['id', 'country_(or_dependency)', 'population_2025', 'yearly_change',
       'net_change', 'density_(p/km²)', 'land_area_(km²)', 'migrants_(net)',
       'fert._rate', 'median_age', 'urban_pop_%', 'world_share'],
      dtype='str')
      id   country_(or_dependency)  population_2025 yearly_change net_change  \
5      6                   Nigeria        237527782         2.08%    4848304
9     10                  Ethiopia        135472051         2.58%    3412284
12    13                     Egypt        118365995         1.57%    1827737
14    15                  DR Congo        112832473         3.25%    3556208
20    21                  Tanzania         70545865          2.9%    1985708
23    24              South Africa         64747319         1.16%     740132
25    26                     Kenya         57532493         1.95%    1099549
29    30                     Sudan         51662147          2.4%    1213184
30    31                    Uganda         51384894         2.74%    1369802
32    33                   Algeria         47435312         1.33%     621004
38    39                    Angola         39040039         3.05%    1154190
40    41                   Morocco         38430770         0.92%     349597
44    45                Mozambique         35631653         2.89%     999887
45    46                     Ghana         35064272         1.85%     636858
48    49                Madagascar         32740678         2.43%     775722
49    50             Côte d'Ivoire         32711547         2.43%     777317
50    51                  Cameroon         29879337         2.59%     755593
53    54                     Niger         27917831         3.28%     885419
57    58                      Mali         25198821         2.94%     720226
58    59              Burkina Faso         24074580         2.23%     525799
61    62                    Malawi         22216120         2.59%     560834
62    63                    Zambia         21913874         2.81%     598918
63    64                      Chad         21003705         3.47%     704582
66    67                   Somalia         19654739          3.4%     645588
67    68                   Senegal         18931966         2.32%     429982
73    74                  Zimbabwe         16950795          1.9%     316422
74    75                    Guinea         15099727         2.34%     344942
75    76                     Benin         14814460         2.43%     351736
76    77                    Rwanda         14569341         2.19%     312774
77    78                   Burundi         14390003         2.44%     342217
79    80                   Tunisia         12348573         0.58%      71464
80    81               South Sudan         12188788         2.05%     245380
95    96                      Togo          9721608         2.17%     206372
101  102              Sierra Leone          8819794         2.06%     177772
104  105                     Libya          7458555         1.05%      77532
111  112                     Congo          6484437         2.39%     151476
116  117                   Liberia          5731206         2.11%     118389
120  121  Central African Republic          5513282         3.43%     182592
123  124                Mauritania          5315065         2.82%     145670
131  132                   Eritrea          3607003         2.02%      71400
137  138                   Namibia          3092816         2.07%      62685
142  143                    Gambia          2822093         2.25%      62105
144  145                     Gabon          2593130         2.13%      54178
145  146                  Botswana          2562122         1.63%      40983
146  147                   Lesotho          2363325         1.11%      25902
147  148             Guinea-Bissau          2249515         2.19%      48163
149  150         Equatorial Guinea          1938431         2.43%      45915
157  158                 Mauritius          1268280        −0.23%     −2,889
158  159                  Eswatini          1256174         1.07%      13352
159  160                  Djibouti          1184076         1.31%      15354
161  162                   Comoros           882847         1.87%      16219
162  163                   Réunion           882405         0.43%       3814
170  171            Western Sahara           600904         1.76%      10398
173  174                Cabo Verde           527326         0.47%       2449
180  181                   Mayotte           337011         3.22%      10506
186  187       Sao Tome & Principe           240254            2%       4718
192  193                Seychelles           132779         1.81%       2361
227  228              Saint Helena             5197        −0.76%        −40

     density_(p/km²)  land_area_(km²) migrants_(net)  fert._rate  median_age  \
5                261           910770        −15,258        4.30        18.1
9                135          1000000          24054        3.81        19.1
12               119           995450        −57,305        2.71        24.5
14                50          2267050        −27,309        5.90        15.8
20                80           885800        −12,730        4.47        17.5
23                53          1213090         146370        2.19        28.7
25               101           569140        −27,330        3.12        20.0
29                29          1765048         291469        4.19        18.5
30               257           199810       −119,059        4.06        16.9
32                20          2381740        −27,531        2.67        28.6
38                31          1246700         −3,524        4.95        16.6
40                86           446300        −56,254        2.18        29.8
44                45           786380        −65,573        4.62        16.5
45               154           227540        −17,079        3.30        21.3
48                56           581795         −2,227        3.85        19.2
49               103           318000          11305        4.17        18.3
50                63           472710        −15,379        4.18        18.0
53                22          1266700         −7,704        5.79        15.6
57                21          1220190        −48,019        5.42        15.7
58                88           273600        −27,130        4.00        17.7
61               236            94280         −5,628        3.53        18.1
62                29           743390           6562        3.97        17.9
63                17          1259200       −123,104        5.94        15.8
66                31           627340          12077        5.91        15.6
67                98           192530        −12,636        3.71        19.6
73                44           386850        −54,555        3.62        18.1
74                61           245720        −16,282        4.04        18.3
75               131           112760         −7,847        4.42        18.0
76               591            24670           6282        3.59        19.9
77               560            25680        −34,727        4.67        16.4
79                79           155360        −14,523        1.80        32.9
80                20           610952           6145        3.71        18.7
95               179            54390        −15,010        4.07        19.1
101              122            72180        −11,309        3.61        19.7
104                4          1759540           −172        2.25        27.7
111               19           341500         −2,999        4.05        18.6
116               60            96320         −9,870        3.79        18.8
120                9           622980        −14,693        5.81        14.5
123                5          1030700         −5,044        4.56        17.4
131               36           101000         −6,698        3.61        19.2
137                4           823290           1866        3.17        21.3
142              279            10120         −2,984        3.80        18.6
144               10           257670           1116        3.54        21.5
145                5           566730         −5,665        2.66        23.4
146               78            30360         −5,192        2.64        21.8
147               80            28120         −1,373        3.68        19.4
149               69            28050           3812        4.04        20.9
157              625             2030         −2,784        1.21        37.8
158               73            17200         −5,775        2.68        22.5
159               51            23180           −581        2.58        24.9
161              474             1861         −2,127        3.76        20.6
162              353             2500         −2,585        2.13        38.1
170                2           266000           5030        2.15        32.6
173              131             4030         −1,284        1.50        29.0
180              899              375             44        4.50        17.1
186              250              960           −650        3.53        19.5
192              289              460           1590        2.08        34.3
227               13              390              1        1.64        50.9

    urban_pop_% world_share
5         54.9%       2.89%
9         22.5%       1.65%
12        40.9%       1.44%
14          45%       1.37%
20          40%       0.86%
23        66.6%       0.79%
25        31.9%       0.70%
29        35.3%       0.63%
30          30%       0.62%
32        74.4%       0.58%
38        68.8%       0.47%
40        67.3%       0.47%
44        41.6%       0.43%
45        58.6%       0.43%
48        40.3%       0.40%
49          49%       0.40%
50        59.4%       0.36%
53        18.2%       0.34%
57        44.4%       0.31%
58        33.7%       0.29%
61        19.8%       0.27%
62        46.8%       0.27%
63        22.4%       0.26%
66        46.6%       0.24%
67        52.3%       0.23%
73        37.9%       0.21%
74        40.3%       0.18%
75        47.8%       0.18%
76        18.3%       0.18%
77        14.9%       0.17%
79        71.7%       0.15%
80        27.7%       0.15%
95        44.2%       0.12%
101       45.5%       0.11%
104       77.5%      0.091%
111       69.8%      0.079%
116         55%      0.070%
120       44.5%      0.067%
123       60.3%      0.065%
131       74.8%      0.044%
137       54.4%      0.038%
142       61.3%      0.034%
144       83.7%      0.032%
145       75.6%      0.031%
146       32.8%      0.029%
147       46.2%      0.027%
149       63.6%      0.024%
157       41.5%      0.015%
158       31.3%      0.015%
159       71.3%      0.014%
161       33.6%      0.011%
162         NaN      0.011%
170         97%     0.0073%
173       78.6%     0.0064%
180       41.4%     0.0041%
186       78.2%     0.0029%
192       43.8%     0.0016%
227       33.4%   0.000063%

In [11]:
# order alphabetically by country name
african_df = african_df.sort_values(by='country_(or_dependency)')
print(african_df)

      id   country_(or_dependency)  population_2025 yearly_change net_change  \
32    33                   Algeria         47435312         1.33%     621004
38    39                    Angola         39040039         3.05%    1154190
75    76                     Benin         14814460         2.43%     351736
145  146                  Botswana          2562122         1.63%      40983
58    59              Burkina Faso         24074580         2.23%     525799
77    78                   Burundi         14390003         2.44%     342217
173  174                Cabo Verde           527326         0.47%       2449
50    51                  Cameroon         29879337         2.59%     755593
120  121  Central African Republic          5513282         3.43%     182592
63    64                      Chad         21003705         3.47%     704582
161  162                   Comoros           882847         1.87%      16219
111  112                     Congo          6484437         2.39%     151476
49    50             Côte d'Ivoire         32711547         2.43%     777317
14    15                  DR Congo        112832473         3.25%    3556208
159  160                  Djibouti          1184076         1.31%      15354
12    13                     Egypt        118365995         1.57%    1827737
149  150         Equatorial Guinea          1938431         2.43%      45915
131  132                   Eritrea          3607003         2.02%      71400
158  159                  Eswatini          1256174         1.07%      13352
9     10                  Ethiopia        135472051         2.58%    3412284
144  145                     Gabon          2593130         2.13%      54178
142  143                    Gambia          2822093         2.25%      62105
45    46                     Ghana         35064272         1.85%     636858
74    75                    Guinea         15099727         2.34%     344942
147  148             Guinea-Bissau          2249515         2.19%      48163
25    26                     Kenya         57532493         1.95%    1099549
146  147                   Lesotho          2363325         1.11%      25902
116  117                   Liberia          5731206         2.11%     118389
104  105                     Libya          7458555         1.05%      77532
48    49                Madagascar         32740678         2.43%     775722
61    62                    Malawi         22216120         2.59%     560834
57    58                      Mali         25198821         2.94%     720226
123  124                Mauritania          5315065         2.82%     145670
157  158                 Mauritius          1268280        −0.23%     −2,889
180  181                   Mayotte           337011         3.22%      10506
40    41                   Morocco         38430770         0.92%     349597
44    45                Mozambique         35631653         2.89%     999887
137  138                   Namibia          3092816         2.07%      62685
53    54                     Niger         27917831         3.28%     885419
5      6                   Nigeria        237527782         2.08%    4848304
76    77                    Rwanda         14569341         2.19%     312774
162  163                   Réunion           882405         0.43%       3814
227  228              Saint Helena             5197        −0.76%        −40
186  187       Sao Tome & Principe           240254            2%       4718
67    68                   Senegal         18931966         2.32%     429982
192  193                Seychelles           132779         1.81%       2361
101  102              Sierra Leone          8819794         2.06%     177772
66    67                   Somalia         19654739          3.4%     645588
23    24              South Africa         64747319         1.16%     740132
80    81               South Sudan         12188788         2.05%     245380
29    30                     Sudan         51662147          2.4%    1213184
20    21                  Tanzania         70545865          2.9%    1985708
95    96                      Togo          9721608         2.17%     206372
79    80                   Tunisia         12348573         0.58%      71464
30    31                    Uganda         51384894         2.74%    1369802
170  171            Western Sahara           600904         1.76%      10398
62    63                    Zambia         21913874         2.81%     598918
73    74                  Zimbabwe         16950795          1.9%     316422

     density_(p/km²)  land_area_(km²) migrants_(net)  fert._rate  median_age  \
32                20          2381740        −27,531        2.67        28.6
38                31          1246700         −3,524        4.95        16.6
75               131           112760         −7,847        4.42        18.0
145                5           566730         −5,665        2.66        23.4
58                88           273600        −27,130        4.00        17.7
77               560            25680        −34,727        4.67        16.4
173              131             4030         −1,284        1.50        29.0
50                63           472710        −15,379        4.18        18.0
120                9           622980        −14,693        5.81        14.5
63                17          1259200       −123,104        5.94        15.8
161              474             1861         −2,127        3.76        20.6
111               19           341500         −2,999        4.05        18.6
49               103           318000          11305        4.17        18.3
14                50          2267050        −27,309        5.90        15.8
159               51            23180           −581        2.58        24.9
12               119           995450        −57,305        2.71        24.5
149               69            28050           3812        4.04        20.9
131               36           101000         −6,698        3.61        19.2
158               73            17200         −5,775        2.68        22.5
9                135          1000000          24054        3.81        19.1
144               10           257670           1116        3.54        21.5
142              279            10120         −2,984        3.80        18.6
45               154           227540        −17,079        3.30        21.3
74                61           245720        −16,282        4.04        18.3
147               80            28120         −1,373        3.68        19.4
25               101           569140        −27,330        3.12        20.0
146               78            30360         −5,192        2.64        21.8
116               60            96320         −9,870        3.79        18.8
104                4          1759540           −172        2.25        27.7
48                56           581795         −2,227        3.85        19.2
61               236            94280         −5,628        3.53        18.1
57                21          1220190        −48,019        5.42        15.7
123                5          1030700         −5,044        4.56        17.4
157              625             2030         −2,784        1.21        37.8
180              899              375             44        4.50        17.1
40                86           446300        −56,254        2.18        29.8
44                45           786380        −65,573        4.62        16.5
137                4           823290           1866        3.17        21.3
53                22          1266700         −7,704        5.79        15.6
5                261           910770        −15,258        4.30        18.1
76               591            24670           6282        3.59        19.9
162              353             2500         −2,585        2.13        38.1
227               13              390              1        1.64        50.9
186              250              960           −650        3.53        19.5
67                98           192530        −12,636        3.71        19.6
192              289              460           1590        2.08        34.3
101              122            72180        −11,309        3.61        19.7
66                31           627340          12077        5.91        15.6
23                53          1213090         146370        2.19        28.7
80                20           610952           6145        3.71        18.7
29                29          1765048         291469        4.19        18.5
20                80           885800        −12,730        4.47        17.5
95               179            54390        −15,010        4.07        19.1
79                79           155360        −14,523        1.80        32.9
30               257           199810       −119,059        4.06        16.9
170                2           266000           5030        2.15        32.6
62                29           743390           6562        3.97        17.9
73                44           386850        −54,555        3.62        18.1

    urban_pop_% world_share
32        74.4%       0.58%
38        68.8%       0.47%
75        47.8%       0.18%
145       75.6%      0.031%
58        33.7%       0.29%
77        14.9%       0.17%
173       78.6%     0.0064%
50        59.4%       0.36%
120       44.5%      0.067%
63        22.4%       0.26%
161       33.6%      0.011%
111       69.8%      0.079%
49          49%       0.40%
14          45%       1.37%
159       71.3%      0.014%
12        40.9%       1.44%
149       63.6%      0.024%
131       74.8%      0.044%
158       31.3%      0.015%
9         22.5%       1.65%
144       83.7%      0.032%
142       61.3%      0.034%
45        58.6%       0.43%
74        40.3%       0.18%
147       46.2%      0.027%
25        31.9%       0.70%
146       32.8%      0.029%
116         55%      0.070%
104       77.5%      0.091%
48        40.3%       0.40%
61        19.8%       0.27%
57        44.4%       0.31%
123       60.3%      0.065%
157       41.5%      0.015%
180       41.4%     0.0041%
40        67.3%       0.47%
44        41.6%       0.43%
137       54.4%      0.038%
53        18.2%       0.34%
5         54.9%       2.89%
76        18.3%       0.18%
162         NaN      0.011%
227       33.4%   0.000063%
186       78.2%     0.0029%
67        52.3%       0.23%
192       43.8%     0.0016%
101       45.5%       0.11%
66        46.6%       0.24%
23        66.6%       0.79%
80        27.7%       0.15%
29        35.3%       0.63%
20          40%       0.86%
95        44.2%       0.12%
79        71.7%       0.15%
30          30%       0.62%
170         97%     0.0073%
62        46.8%       0.27%
73        37.9%       0.21%

In [12]:
# remove indexes
african_df = african_df.reset_index(drop=True)
print(african_df)

     id   country_(or_dependency)  population_2025 yearly_change net_change  \
0    33                   Algeria         47435312         1.33%     621004
1    39                    Angola         39040039         3.05%    1154190
2    76                     Benin         14814460         2.43%     351736
3   146                  Botswana          2562122         1.63%      40983
4    59              Burkina Faso         24074580         2.23%     525799
5    78                   Burundi         14390003         2.44%     342217
6   174                Cabo Verde           527326         0.47%       2449
7    51                  Cameroon         29879337         2.59%     755593
8   121  Central African Republic          5513282         3.43%     182592
9    64                      Chad         21003705         3.47%     704582
10  162                   Comoros           882847         1.87%      16219
11  112                     Congo          6484437         2.39%     151476
12   50             Côte d'Ivoire         32711547         2.43%     777317
13   15                  DR Congo        112832473         3.25%    3556208
14  160                  Djibouti          1184076         1.31%      15354
15   13                     Egypt        118365995         1.57%    1827737
16  150         Equatorial Guinea          1938431         2.43%      45915
17  132                   Eritrea          3607003         2.02%      71400
18  159                  Eswatini          1256174         1.07%      13352
19   10                  Ethiopia        135472051         2.58%    3412284
20  145                     Gabon          2593130         2.13%      54178
21  143                    Gambia          2822093         2.25%      62105
22   46                     Ghana         35064272         1.85%     636858
23   75                    Guinea         15099727         2.34%     344942
24  148             Guinea-Bissau          2249515         2.19%      48163
25   26                     Kenya         57532493         1.95%    1099549
26  147                   Lesotho          2363325         1.11%      25902
27  117                   Liberia          5731206         2.11%     118389
28  105                     Libya          7458555         1.05%      77532
29   49                Madagascar         32740678         2.43%     775722
30   62                    Malawi         22216120         2.59%     560834
31   58                      Mali         25198821         2.94%     720226
32  124                Mauritania          5315065         2.82%     145670
33  158                 Mauritius          1268280        −0.23%     −2,889
34  181                   Mayotte           337011         3.22%      10506
35   41                   Morocco         38430770         0.92%     349597
36   45                Mozambique         35631653         2.89%     999887
37  138                   Namibia          3092816         2.07%      62685
38   54                     Niger         27917831         3.28%     885419
39    6                   Nigeria        237527782         2.08%    4848304
40   77                    Rwanda         14569341         2.19%     312774
41  163                   Réunion           882405         0.43%       3814
42  228              Saint Helena             5197        −0.76%        −40
43  187       Sao Tome & Principe           240254            2%       4718
44   68                   Senegal         18931966         2.32%     429982
45  193                Seychelles           132779         1.81%       2361
46  102              Sierra Leone          8819794         2.06%     177772
47   67                   Somalia         19654739          3.4%     645588
48   24              South Africa         64747319         1.16%     740132
49   81               South Sudan         12188788         2.05%     245380
50   30                     Sudan         51662147          2.4%    1213184
51   21                  Tanzania         70545865          2.9%    1985708
52   96                      Togo          9721608         2.17%     206372
53   80                   Tunisia         12348573         0.58%      71464
54   31                    Uganda         51384894         2.74%    1369802
55  171            Western Sahara           600904         1.76%      10398
56   63                    Zambia         21913874         2.81%     598918
57   74                  Zimbabwe         16950795          1.9%     316422

    density_(p/km²)  land_area_(km²) migrants_(net)  fert._rate  median_age  \
0                20          2381740        −27,531        2.67        28.6
1                31          1246700         −3,524        4.95        16.6
2               131           112760         −7,847        4.42        18.0
3                 5           566730         −5,665        2.66        23.4
4                88           273600        −27,130        4.00        17.7
5               560            25680        −34,727        4.67        16.4
6               131             4030         −1,284        1.50        29.0
7                63           472710        −15,379        4.18        18.0
8                 9           622980        −14,693        5.81        14.5
9                17          1259200       −123,104        5.94        15.8
10              474             1861         −2,127        3.76        20.6
11               19           341500         −2,999        4.05        18.6
12              103           318000          11305        4.17        18.3
13               50          2267050        −27,309        5.90        15.8
14               51            23180           −581        2.58        24.9
15              119           995450        −57,305        2.71        24.5
16               69            28050           3812        4.04        20.9
17               36           101000         −6,698        3.61        19.2
18               73            17200         −5,775        2.68        22.5
19              135          1000000          24054        3.81        19.1
20               10           257670           1116        3.54        21.5
21              279            10120         −2,984        3.80        18.6
22              154           227540        −17,079        3.30        21.3
23               61           245720        −16,282        4.04        18.3
24               80            28120         −1,373        3.68        19.4
25              101           569140        −27,330        3.12        20.0
26               78            30360         −5,192        2.64        21.8
27               60            96320         −9,870        3.79        18.8
28                4          1759540           −172        2.25        27.7
29               56           581795         −2,227        3.85        19.2
30              236            94280         −5,628        3.53        18.1
31               21          1220190        −48,019        5.42        15.7
32                5          1030700         −5,044        4.56        17.4
33              625             2030         −2,784        1.21        37.8
34              899              375             44        4.50        17.1
35               86           446300        −56,254        2.18        29.8
36               45           786380        −65,573        4.62        16.5
37                4           823290           1866        3.17        21.3
38               22          1266700         −7,704        5.79        15.6
39              261           910770        −15,258        4.30        18.1
40              591            24670           6282        3.59        19.9
41              353             2500         −2,585        2.13        38.1
42               13              390              1        1.64        50.9
43              250              960           −650        3.53        19.5
44               98           192530        −12,636        3.71        19.6
45              289              460           1590        2.08        34.3
46              122            72180        −11,309        3.61        19.7
47               31           627340          12077        5.91        15.6
48               53          1213090         146370        2.19        28.7
49               20           610952           6145        3.71        18.7
50               29          1765048         291469        4.19        18.5
51               80           885800        −12,730        4.47        17.5
52              179            54390        −15,010        4.07        19.1
53               79           155360        −14,523        1.80        32.9
54              257           199810       −119,059        4.06        16.9
55                2           266000           5030        2.15        32.6
56               29           743390           6562        3.97        17.9
57               44           386850        −54,555        3.62        18.1

   urban_pop_% world_share
0        74.4%       0.58%
1        68.8%       0.47%
2        47.8%       0.18%
3        75.6%      0.031%
4        33.7%       0.29%
5        14.9%       0.17%
6        78.6%     0.0064%
7        59.4%       0.36%
8        44.5%      0.067%
9        22.4%       0.26%
10       33.6%      0.011%
11       69.8%      0.079%
12         49%       0.40%
13         45%       1.37%
14       71.3%      0.014%
15       40.9%       1.44%
16       63.6%      0.024%
17       74.8%      0.044%
18       31.3%      0.015%
19       22.5%       1.65%
20       83.7%      0.032%
21       61.3%      0.034%
22       58.6%       0.43%
23       40.3%       0.18%
24       46.2%      0.027%
25       31.9%       0.70%
26       32.8%      0.029%
27         55%      0.070%
28       77.5%      0.091%
29       40.3%       0.40%
30       19.8%       0.27%
31       44.4%       0.31%
32       60.3%      0.065%
33       41.5%      0.015%
34       41.4%     0.0041%
35       67.3%       0.47%
36       41.6%       0.43%
37       54.4%      0.038%
38       18.2%       0.34%
39       54.9%       2.89%
40       18.3%       0.18%
41         NaN      0.011%
42       33.4%   0.000063%
43       78.2%     0.0029%
44       52.3%       0.23%
45       43.8%     0.0016%
46       45.5%       0.11%
47       46.6%       0.24%
48       66.6%       0.79%
49       27.7%       0.15%
50       35.3%       0.63%
51         40%       0.86%
52       44.2%       0.12%
53       71.7%       0.15%
54         30%       0.62%
55         97%     0.0073%
56       46.8%       0.27%
57       37.9%       0.21%

In [13]:
# remove id
african_df = african_df.drop(columns=['id'])
print(african_df)

     country_(or_dependency)  population_2025 yearly_change net_change  \
0                    Algeria         47435312         1.33%     621004
1                     Angola         39040039         3.05%    1154190
2                      Benin         14814460         2.43%     351736
3                   Botswana          2562122         1.63%      40983
4               Burkina Faso         24074580         2.23%     525799
5                    Burundi         14390003         2.44%     342217
6                 Cabo Verde           527326         0.47%       2449
7                   Cameroon         29879337         2.59%     755593
8   Central African Republic          5513282         3.43%     182592
9                       Chad         21003705         3.47%     704582
10                   Comoros           882847         1.87%      16219
11                     Congo          6484437         2.39%     151476
12             Côte d'Ivoire         32711547         2.43%     777317
13                  DR Congo        112832473         3.25%    3556208
14                  Djibouti          1184076         1.31%      15354
15                     Egypt        118365995         1.57%    1827737
16         Equatorial Guinea          1938431         2.43%      45915
17                   Eritrea          3607003         2.02%      71400
18                  Eswatini          1256174         1.07%      13352
19                  Ethiopia        135472051         2.58%    3412284
20                     Gabon          2593130         2.13%      54178
21                    Gambia          2822093         2.25%      62105
22                     Ghana         35064272         1.85%     636858
23                    Guinea         15099727         2.34%     344942
24             Guinea-Bissau          2249515         2.19%      48163
25                     Kenya         57532493         1.95%    1099549
26                   Lesotho          2363325         1.11%      25902
27                   Liberia          5731206         2.11%     118389
28                     Libya          7458555         1.05%      77532
29                Madagascar         32740678         2.43%     775722
30                    Malawi         22216120         2.59%     560834
31                      Mali         25198821         2.94%     720226
32                Mauritania          5315065         2.82%     145670
33                 Mauritius          1268280        −0.23%     −2,889
34                   Mayotte           337011         3.22%      10506
35                   Morocco         38430770         0.92%     349597
36                Mozambique         35631653         2.89%     999887
37                   Namibia          3092816         2.07%      62685
38                     Niger         27917831         3.28%     885419
39                   Nigeria        237527782         2.08%    4848304
40                    Rwanda         14569341         2.19%     312774
41                   Réunion           882405         0.43%       3814
42              Saint Helena             5197        −0.76%        −40
43       Sao Tome & Principe           240254            2%       4718
44                   Senegal         18931966         2.32%     429982
45                Seychelles           132779         1.81%       2361
46              Sierra Leone          8819794         2.06%     177772
47                   Somalia         19654739          3.4%     645588
48              South Africa         64747319         1.16%     740132
49               South Sudan         12188788         2.05%     245380
50                     Sudan         51662147          2.4%    1213184
51                  Tanzania         70545865          2.9%    1985708
52                      Togo          9721608         2.17%     206372
53                   Tunisia         12348573         0.58%      71464
54                    Uganda         51384894         2.74%    1369802
55            Western Sahara           600904         1.76%      10398
56                    Zambia         21913874         2.81%     598918
57                  Zimbabwe         16950795          1.9%     316422

    density_(p/km²)  land_area_(km²) migrants_(net)  fert._rate  median_age  \
0                20          2381740        −27,531        2.67        28.6
1                31          1246700         −3,524        4.95        16.6
2               131           112760         −7,847        4.42        18.0
3                 5           566730         −5,665        2.66        23.4
4                88           273600        −27,130        4.00        17.7
5               560            25680        −34,727        4.67        16.4
6               131             4030         −1,284        1.50        29.0
7                63           472710        −15,379        4.18        18.0
8                 9           622980        −14,693        5.81        14.5
9                17          1259200       −123,104        5.94        15.8
10              474             1861         −2,127        3.76        20.6
11               19           341500         −2,999        4.05        18.6
12              103           318000          11305        4.17        18.3
13               50          2267050        −27,309        5.90        15.8
14               51            23180           −581        2.58        24.9
15              119           995450        −57,305        2.71        24.5
16               69            28050           3812        4.04        20.9
17               36           101000         −6,698        3.61        19.2
18               73            17200         −5,775        2.68        22.5
19              135          1000000          24054        3.81        19.1
20               10           257670           1116        3.54        21.5
21              279            10120         −2,984        3.80        18.6
22              154           227540        −17,079        3.30        21.3
23               61           245720        −16,282        4.04        18.3
24               80            28120         −1,373        3.68        19.4
25              101           569140        −27,330        3.12        20.0
26               78            30360         −5,192        2.64        21.8
27               60            96320         −9,870        3.79        18.8
28                4          1759540           −172        2.25        27.7
29               56           581795         −2,227        3.85        19.2
30              236            94280         −5,628        3.53        18.1
31               21          1220190        −48,019        5.42        15.7
32                5          1030700         −5,044        4.56        17.4
33              625             2030         −2,784        1.21        37.8
34              899              375             44        4.50        17.1
35               86           446300        −56,254        2.18        29.8
36               45           786380        −65,573        4.62        16.5
37                4           823290           1866        3.17        21.3
38               22          1266700         −7,704        5.79        15.6
39              261           910770        −15,258        4.30        18.1
40              591            24670           6282        3.59        19.9
41              353             2500         −2,585        2.13        38.1
42               13              390              1        1.64        50.9
43              250              960           −650        3.53        19.5
44               98           192530        −12,636        3.71        19.6
45              289              460           1590        2.08        34.3
46              122            72180        −11,309        3.61        19.7
47               31           627340          12077        5.91        15.6
48               53          1213090         146370        2.19        28.7
49               20           610952           6145        3.71        18.7
50               29          1765048         291469        4.19        18.5
51               80           885800        −12,730        4.47        17.5
52              179            54390        −15,010        4.07        19.1
53               79           155360        −14,523        1.80        32.9
54              257           199810       −119,059        4.06        16.9
55                2           266000           5030        2.15        32.6
56               29           743390           6562        3.97        17.9
57               44           386850        −54,555        3.62        18.1

   urban_pop_% world_share
0        74.4%       0.58%
1        68.8%       0.47%
2        47.8%       0.18%
3        75.6%      0.031%
4        33.7%       0.29%
5        14.9%       0.17%
6        78.6%     0.0064%
7        59.4%       0.36%
8        44.5%      0.067%
9        22.4%       0.26%
10       33.6%      0.011%
11       69.8%      0.079%
12         49%       0.40%
13         45%       1.37%
14       71.3%      0.014%
15       40.9%       1.44%
16       63.6%      0.024%
17       74.8%      0.044%
18       31.3%      0.015%
19       22.5%       1.65%
20       83.7%      0.032%
21       61.3%      0.034%
22       58.6%       0.43%
23       40.3%       0.18%
24       46.2%      0.027%
25       31.9%       0.70%
26       32.8%      0.029%
27         55%      0.070%
28       77.5%      0.091%
29       40.3%       0.40%
30       19.8%       0.27%
31       44.4%       0.31%
32       60.3%      0.065%
33       41.5%      0.015%
34       41.4%     0.0041%
35       67.3%       0.47%
36       41.6%       0.43%
37       54.4%      0.038%
38       18.2%       0.34%
39       54.9%       2.89%
40       18.3%       0.18%
41         NaN      0.011%
42       33.4%   0.000063%
43       78.2%     0.0029%
44       52.3%       0.23%
45       43.8%     0.0016%
46       45.5%       0.11%
47       46.6%       0.24%
48       66.6%       0.79%
49       27.7%       0.15%
50       35.3%       0.63%
51         40%       0.86%
52       44.2%       0.12%
53       71.7%       0.15%
54         30%       0.62%
55         97%     0.0073%
56       46.8%       0.27%
57       37.9%       0.21%

In [14]:
# give me the remaining (exclusing African dataset) as "other_df"
other_df = pop_df[~pop_df['country_(or_dependency)'].isin(african_nations)]
print(other_df)

      id country_(or_dependency)  population_2025 yearly_change  net_change  \
0      1                   India       1463865525         0.89%    12929734
1      2                   China       1416096094        −0.23%  −3,225,184
2      3           United States        347275807         0.54%     1849236
3      4               Indonesia        285721236         0.79%     2233305
4      5                Pakistan        255219554         1.57%     3950390
..   ...                     ...              ...           ...         ...
228  229              Montserrat             4359        −0.68%         −30
229  230        Falkland Islands             3469        −0.03%          −1
230  231                 Tokelau             2608         4.07%         102
231  232                    Niue             1821         0.11%           2
232  233                Holy See              501         1.01%           5

     density_(p/km²)  land_area_(km²) migrants_(net)  fert._rate  median_age  \
0                492          2973190       −495,753        1.94        28.8
1                151          9388211       −268,126        1.02        40.1
2                 38          9147420        1230663        1.62        38.5
3                158          1811570        −39,509        2.10        30.4
4                331           770880     −1,235,336        3.50        20.6
..               ...              ...            ...         ...         ...
228               44              100             −9        1.45        41.6
229                0            12170            −17        1.70        42.8
230              261               10             53        2.57        27.3
231                7              260              3        2.46        35.7
232             1253                0             13        1.00        57.4

    urban_pop_% world_share
0         37.1%      17.78%
1         67.5%      17.20%
2         82.8%       4.22%
3         59.6%       3.47%
4         34.4%       3.10%
..          ...         ...
228       11.5%   0.000053%
229         68%   0.000042%
230         NaN   0.000032%
231       44.5%   0.000022%
232         NaN  0.0000061%

[175 rows x 12 columns]

In [15]:
# order other_df alphabetically by country name
other_df = other_df.sort_values(by='country_(or_dependency)')
print(other_df)

      id country_(or_dependency)  population_2025 yearly_change net_change  \
35    36             Afghanistan         43844111         2.81%    1196619
143  144                 Albania          2771508        −0.73%    −20,257
209  210          American Samoa            46029        −1.57%       −736
201  202                 Andorra            82904         1.18%        966
220  221                Anguilla            14728         0.89%        130
..   ...                     ...              ...           ...        ...
181  182                 Vanuatu           335169         2.26%       7392
52    53               Venezuela         28516896         0.39%     111353
15    16                 Vietnam        101598527          0.6%     610841
224  225         Wallis & Futuna            11194        −0.74%        −83
36    37                   Yemen         41773878         2.93%    1190714

     density_(p/km²)  land_area_(km²) migrants_(net)  fert._rate  median_age  \
35                67           652860        −74,404        4.66        17.3
143              101            27400        −24,230        1.33        37.3
209              230              200         −1,051        2.25        29.0
201              176              470            843        1.10        43.9
220              164               90             70        1.35        38.7
..               ...              ...            ...         ...         ...
181               27            12190            −52        3.53        20.3
52                32           882050       −100,467        2.06        29.4
15               328           310070        −48,171        1.88        33.4
224               80              140            −83        1.40        38.2
36                79           527970        −16,291        4.41        18.4

    urban_pop_% world_share
35        26.7%       0.53%
143       70.3%      0.034%
209         NaN    0.00056%
201       82.3%     0.0010%
220         NaN    0.00018%
..          ...         ...
181       25.4%     0.0041%
52          NaN       0.35%
15        41.4%       1.23%
224         NaN    0.00014%
36          33%       0.51%

[175 rows x 12 columns]